
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\UmutcanEkinci\Desktop\dev\python\todo-app\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x550")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 550,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    40.0,
    700.0,
    550.0,
    fill="#222831",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    700.0,
    40.0,
    fill="#00ADB5",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=500.0,
    y=7.5,
    width=91.0,
    height=25.0
)

canvas.create_text(
    539.0,
    8.0,
    anchor="nw",
    text="+",
    fill="#FFFFFF",
    font=("Inter", 17 * -1)
)

canvas.create_text(
    52.0,
    11.0,
    anchor="nw",
    text="TO DO LIST",
    fill="#EEEEEE",
    font=("Inter", 17 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    32.0,
    21.0,
    image=image_image_1
)

canvas.create_rectangle(
    20.0,
    54.0,
    680.0,
    526.0,
    fill="#393E46",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=460.0,
    y=54.0,
    width=220.0,
    height=37.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=240.0,
    y=54.0,
    width=220.0,
    height=37.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=20.0,
    y=54.0,
    width=220.0,
    height=37.0
)

canvas.create_text(
    106.0,
    62.0,
    anchor="nw",
    text="OPEN",
    fill="#FFFFFF",
    font=("Inter", 17 * -1)
)

canvas.create_text(
    293.0,
    62.0,
    anchor="nw",
    text="IN PROGRESS",
    fill="#FFFFFF",
    font=("Inter", 17 * -1)
)

canvas.create_text(
    545.0,
    62.0,
    anchor="nw",
    text="DONE",
    fill="#FFFFFF",
    font=("Inter", 17 * -1)
)

canvas.create_rectangle(
    20.0,
    91.0,
    680.0,
    138.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    41.0,
    105.0,
    anchor="nw",
    text="Task 1",
    fill="#000000",
    font=("Inter", 17 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=667.0,
    y=8.0,
    width=24.0,
    height=23.278194427490234
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=635.0,
    y=7.5,
    width=25.0,
    height=25.0
)

canvas.create_rectangle(
    635.0,
    17.0,
    660.0,
    22.0,
    fill="#D9D9D9",
    outline="")

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=606.0,
    y=9.0,
    width=24.0,
    height=24.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    617.7999877929688,
    21.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
